services:
  postgres:
    image: postgres:16-alpine
    container_name: fincheck_postgres
    environment:
      POSTGRES_USER: fincheck
      POSTGRES_PASSWORD: fincheck
      POSTGRES_DB: fincheck
    ports:
      - "5544:5432"
    volumes:
      - fincheck_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fincheck -d fincheck"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  fincheck_pgdata:
