"""add deleted_at to expenses

Revision ID: 52fb15060eb0
Revises: 82e8d2e4be8c
Create Date: 2026-06-11 16:05:47.432516

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "52fb15060eb0"
down_revision = "82e8d2e4be8c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("expenses", schema=None) as batch_op:
        batch_op.drop_column("deleted_at")

    # ### end Alembic commands ###
