"""add last_login_at to users

Revision ID: 82e8d2e4be8c
Revises: 62c93c91bce3
Create Date: 2026-05-20 10:10:08.080386

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82e8d2e4be8c"
down_revision = "62c93c91bce3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("last_login_at")

    # ### end Alembic commands ###
