"""add avatar_filename to users

Revision ID: f3a8c7d2e1b4
Revises: ad91b9833ed6
Create Date: 2026-06-11 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f3a8c7d2e1b4"
down_revision = "ad91b9833ed6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("avatar_filename", sa.String(255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("avatar_filename")

    # ### end Alembic commands ###
